package model

import "sort"

type ISO3166t map[string]CountryData

type CountryData struct {
	Name string
}

var SortedKeys []string

var ISO3166 = ISO3166t{
	"AD": {Name: "Andorra"},
	"AE": {Name: "United Arab Emirates"},
	"AF": {Name: "Afghanistan"},
	"AG": {Name: "Antigua and Barbuda"},
	"AI": {Name: "Anguilla"},
	"AL": {Name: "Albania"},
	"AM": {Name: "Armenia"},
	"AN": {Name: "Netherlands Antilles"},
	"AO": {Name: "Angola"},
	"AQ": {Name: "Antarctica"},
	"AR": {Name: "Argentina"},
	"AS": {Name: "American Samoa"},
	"AT": {Name: "Austria"},
	"AU": {Name: "Australia"},
	"AW": {Name: "Aruba"},
	"AX": {Name: "Åland Islands"},
	"AZ": {Name: "Azerbaijan"},
	"BA": {Name: "Bosnia and Herzegovina"},
	"BB": {Name: "Barbados"},
	"BD": {Name: "Bangladesh"},
	"BE": {Name: "Belgium"},
	"BF": {Name: "Burkina Faso"},
	"BG": {Name: "Bulgaria"},
	"BH": {Name: "Bahrain"},
	"BI": {Name: "Burundi"},
	"BJ": {Name: "Benin"},
	"BL": {Name: "Saint Barthélemy"},
	"BM": {Name: "Bermuda"},
	"BN": {Name: "Brunei"},
	"BO": {Name: "Bolivia"},
	"BQ": {Name: "Bonaire, Sint Eustatius and Saba"},
	"BR": {Name: "Brazil"},
	"BS": {Name: "Bahamas"},
	"BT": {Name: "Bhutan"},
	"BV": {Name: "Bouvet Island"},
	"BW": {Name: "Botswana"},
	"BY": {Name: "Belarus"},
	"BZ": {Name: "Belize"},
	"CA": {Name: "Canada"},
	"CC": {Name: "Cocos (Keeling) Islands"},
	"CD": {Name: "Congo, the Democratic Republic of the"},
	"CF": {Name: "Central African Republic"},
	"CG": {Name: "Congo"},
	"CH": {Name: "Switzerland"},
	"CI": {Name: "Ivory Coast"},
	"CK": {Name: "Cook Islands"},
	"CL": {Name: "Chile"},
	"CM": {Name: "Cameroon"},
	"CN": {Name: "China"},
	"CO": {Name: "Colombia"},
	"CR": {Name: "Costa Rica"},
	"CU": {Name: "Cuba"},
	"CV": {Name: "Cape Verde"},
	"CW": {Name: "Curaçao"},
	"CX": {Name: "Christmas Island"},
	"CY": {Name: "Cyprus"},
	"CZ": {Name: "Czech Republic"},
	"DE": {Name: "Germany"},
	"DJ": {Name: "Djibouti"},
	"DK": {Name: "Denmark"},
	"DM": {Name: "Dominica"},
	"DO": {Name: "Dominican Republic"},
	"DZ": {Name: "Algeria"},
	"EC": {Name: "Ecuador"},
	"EE": {Name: "Estonia"},
	"EG": {Name: "Egypt"},
	"EH": {Name: "Western Sahara"},
	"ER": {Name: "Eritrea"},
	"ES": {Name: "Spain"},
	"ET": {Name: "Ethiopia"},
	"FI": {Name: "Finland"},
	"FJ": {Name: "Fiji"},
	"FK": {Name: "Falkland Islands (Malvinas)"},
	"FM": {Name: "Micronesia, Federated States of"},
	"FO": {Name: "Faroe Islands"},
	"FR": {Name: "France"},
	"GA": {Name: "Gabon"},
	"GB": {Name: "United Kingdom"},
	"GD": {Name: "Grenada"},
	"GE": {Name: "Georgia"},
	"GF": {Name: "French Guiana"},
	"GG": {Name: "Guernsey"},
	"GH": {Name: "Ghana"},
	"GI": {Name: "Gibraltar"},
	"GL": {Name: "Greenland"},
	"GM": {Name: "Gambia"},
	"GN": {Name: "Guinea"},
	"GP": {Name: "Guadeloupe"},
	"GQ": {Name: "Equatorial Guinea"},
	"GR": {Name: "Greece"},
	"GS": {Name: "South Georgia and the South Sandwich Islands"},
	"GT": {Name: "Guatemala"},
	"GU": {Name: "Guam"},
	"GW": {Name: "Guinea-Bissau"},
	"GY": {Name: "Guyana"},
	"HK": {Name: "Hong Kong"},
	"HM": {Name: "Heard Island and McDonald Islands"},
	"HN": {Name: "Honduras"},
	"HR": {Name: "Croatia"},
	"HT": {Name: "Haiti"},
	"HU": {Name: "Hungary"},
	"ID": {Name: "Indonesia"},
	"IE": {Name: "Ireland"},
	"IL": {Name: "Israel"},
	"IM": {Name: "Isle of Man"},
	"IN": {Name: "India"},
	"IO": {Name: "British Indian Ocean Territory"},
	"IQ": {Name: "Iraq"},
	"IR": {Name: "Iran, Islamic Republic of"},
	"IS": {Name: "Iceland"},
	"IT": {Name: "Italy"},
	"JE": {Name: "Jersey"},
	"JM": {Name: "Jamaica"},
	"JO": {Name: "Jordan"},
	"JP": {Name: "Japan"},
	"KE": {Name: "Kenya"},
	"KG": {Name: "Kyrgyzstan"},
	"KH": {Name: "Cambodia"},
	"KI": {Name: "Kiribati"},
	"KM": {Name: "Comoros"},
	"KN": {Name: "Saint Kitts and Nevis"},
	"KP": {Name: "Korea, Democratic People's Republic of"},
	"KR": {Name: "Korea, Republic of"},
	"KW": {Name: "Kuwait"},
	"KY": {Name: "Cayman Islands"},
	"KZ": {Name: "Kazakhstan"},
	"LA": {Name: "Lao People's Democratic Republic"},
	"LB": {Name: "Lebanon"},
	"LC": {Name: "Saint Lucia"},
	"LI": {Name: "Liechtenstein"},
	"LK": {Name: "Sri Lanka"},
	"LR": {Name: "Liberia"},
	"LS": {Name: "Lesotho"},
	"LT": {Name: "Lithuania"},
	"LU": {Name: "Luxembourg"},
	"LV": {Name: "Latvia"},
	"LY": {Name: "Libya"},
	"MA": {Name: "Morocco"},
	"MC": {Name: "Monaco"},
	"MD": {Name: "Moldova, Republic of"},
	"ME": {Name: "Montenegro"},
	"MF": {Name: "Saint Martin (French part)"},
	"MG": {Name: "Madagascar"},
	"MH": {Name: "Marshall Islands"},
	"MK": {Name: "Macedonia, the former Yugoslav Republic of"},
	"ML": {Name: "Mali"},
	"MM": {Name: "Burma"},
	"MN": {Name: "Mongolia"},
	"MO": {Name: "Macao"},
	"MP": {Name: "Northern Mariana Islands"},
	"MQ": {Name: "Martinique"},
	"MR": {Name: "Mauritania"},
	"MS": {Name: "Montserrat"},
	"MT": {Name: "Malta"},
	"MU": {Name: "Mauritius"},
	"MV": {Name: "Maldives"},
	"MW": {Name: "Malawi"},
	"MX": {Name: "Mexico"},
	"MY": {Name: "Malaysia"},
	"MZ": {Name: "Mozambique"},
	"NA": {Name: "Namibia"},
	"NC": {Name: "New Caledonia"},
	"NE": {Name: "Niger"},
	"NF": {Name: "Norfolk Island"},
	"NG": {Name: "Nigeria"},
	"NI": {Name: "Nicaragua"},
	"NL": {Name: "Netherlands"},
	"NO": {Name: "Norway"},
	"NP": {Name: "Nepal"},
	"NR": {Name: "Nauru"},
	"NU": {Name: "Niue"},
	"NZ": {Name: "New Zealand"},
	"OM": {Name: "Oman"},
	"PA": {Name: "Panama"},
	"PE": {Name: "Peru"},
	"PF": {Name: "French Polynesia"},
	"PG": {Name: "Papua New Guinea"},
	"PH": {Name: "Philippines"},
	"PK": {Name: "Pakistan"},
	"PL": {Name: "Poland"},
	"PM": {Name: "Saint Pierre and Miquelon"},
	"PN": {Name: "Pitcairn"},
	"PR": {Name: "Puerto Rico"},
	"PS": {Name: "Palestinian Territory, Occupied"},
	"PT": {Name: "Portugal"},
	"PW": {Name: "Palau"},
	"PY": {Name: "Paraguay"},
	"QA": {Name: "Qatar"},
	"RE": {Name: "Réunion"},
	"RO": {Name: "Romania"},
	"RS": {Name: "Serbia"},
	"RU": {Name: "Russia"},
	"RW": {Name: "Rwanda"},
	"SA": {Name: "Saudi Arabia"},
	"SB": {Name: "Solomon Islands"},
	"SC": {Name: "Seychelles"},
	"SD": {Name: "Sudan"},
	"SE": {Name: "Sweden"},
	"SG": {Name: "Singapore"},
	"SH": {Name: "Saint Helena, Ascension and Tristan da Cunha"},
	"SI": {Name: "Slovenia"},
	"SJ": {Name: "Svalbard and Jan Mayen"},
	"SK": {Name: "Slovakia"},
	"SL": {Name: "Sierra Leone"},
	"SM": {Name: "San Marino"},
	"SN": {Name: "Senegal"},
	"SO": {Name: "Somalia"},
	"SR": {Name: "Suriname"},
	"SS": {Name: "South Sudan"},
	"ST": {Name: "Sao Tome and Principe"},
	"SV": {Name: "El Salvador"},
	"SX": {Name: "Sint Maarten (Dutch part)"},
	"SY": {Name: "Syrian Arab Republic"},
	"SZ": {Name: "Swaziland"},
	"TC": {Name: "Turks and Caicos Islands"},
	"TD": {Name: "Chad"},
	"TF": {Name: "French Southern Territories"},
	"TG": {Name: "Togo"},
	"TH": {Name: "Thailand"},
	"TJ": {Name: "Tajikistan"},
	"TK": {Name: "Tokelau"},
	"TL": {Name: "Timor-Leste"},
	"TM": {Name: "Turkmenistan"},
	"TN": {Name: "Tunisia"},
	"TO": {Name: "Tonga"},
	"TR": {Name: "Turkey"},
	"TT": {Name: "Trinidad and Tobago"},
	"TV": {Name: "Tuvalu"},
	"TW": {Name: "Taiwan"},
	"TZ": {Name: "Tanzania, United Republic of"},
	"UA": {Name: "Ukraine"},
	"UG": {Name: "Uganda"},
	"UM": {Name: "United States Minor Outlying Islands"},
	"US": {Name: "United States"},
	"UY": {Name: "Uruguay"},
	"UZ": {Name: "Uzbekistan"},
	"VA": {Name: "Holy See (Vatican City State)"},
	"VC": {Name: "St. Vincent and the Grenadines"},
	"VE": {Name: "Venezuela"},
	"VG": {Name: "Virgin Islands, British"},
	"VI": {Name: "Virgin Islands, U.S."},
	"VN": {Name: "Vietnam"},
	"VU": {Name: "Vanuatu"},
	"WF": {Name: "Wallis and Futuna"},
	"WS": {Name: "Samoa"},
	"XK": {Name: "Kosovo"},
	"YE": {Name: "Yemen"},
	"YT": {Name: "Mayotte"},
	"ZA": {Name: "South Africa"},
	"ZM": {Name: "Zambia"},
	"ZW": {Name: "Zimbabwe"},
	// Add more countries as needed
}

func init() {
	for key := range ISO3166 {
		SortedKeys = append(SortedKeys, key)
	}
	sort.Strings(SortedKeys)
}
